---
title: "R Notebook"
output: html_notebook
---

```{r Loading Packages, echo=TRUE}
#Classification Project - Water Potability
#Parnian Azimzadeh
#July 2022
#Loading Packages
# general
library(MASS)
library(caret)
library(tidyverse)
library(knitr)
library(kableExtra)

# specific
library(e1071)
library(nnet)
library(pROC)
library(ellipse)
library(rpart)
library(rpart.plot)
library(dplyr)
library(caret)
library(pROC)
```

```{r Data Prepration, echo=TRUE}
#Changing Class to factor
water = read.csv(file = 'water_potability.csv')
glimpse(water)

#show NA
water %>%
  summarise_all(~ sum(is.na(.)))


#Cleaning Data
water$Potability = as.factor(water$Potability)
water_clean = water %>% 
  group_by(Potability) %>%
  mutate(across(where(is.numeric), ~if_else(is.na(.), mean(., na.rm = T), as.numeric(.)))) %>% ungroup()
glimpse(water_clean)

water_clean %>% 
  group_by(Potability) %>% 
  summarise(n = n())

ggplot(data = water_clean, aes(x = Potability, fill = Potability)) + 
  geom_bar(colour="black") +
  ggtitle("Plot of water potability") +
  xlab("Potability") + 
  scale_fill_manual(values = c("cornsilk2", "darkslategray3"),
                    name = "",labels = c("Undrinkable", "Drinkable"),
                                         guide = guide_legend(reverse = TRUE))
```

```{r Exploratory Data Analysis, echo=TRUE}
#Boxplot
water_clean %>%
  pivot_longer(cols = -Potability, names_to = "feature") %>%
  ggplot(aes(x = feature, y = value)) +
  geom_jitter(aes(y = value, col = Potability), alpha = 0.1) +
  geom_boxplot(aes(fill = Potability)) +
  facet_wrap(vars(feature), ncol = 3, scales = "free") +
  scale_color_manual(values = c("cornsilk2", "darkslategray3"),labels=c('Undrinkable', 'Drinkable')) +
  scale_fill_manual(values = c("cornsilk2", "darkslategray3"),labels=c('Undrinkable', 'Drinkable')) +
  theme(
    legend.position = "right",
    strip.background = element_rect(fill = "#0B2D5B"),
    strip.text = element_text(color = "white", face = "bold", size = 8)) +
  labs(
    title = "Detect Outliers With Boxplot",
    subtitle = "Plot, Box and Jitter Plot",
    x = NULL,
    y = NULL,
    fill = NULL,
    color = NULL)

#Histogram
water_clean %>%
  pivot_longer(cols = -Potability, names_to = "feature") %>%
  ggplot(aes(x = value)) +
  geom_histogram(bins = 30, aes(fill = feature)) +
  facet_wrap(vars(feature, Potability), ncol = 4, scales = "free") +
  scale_fill_brewer(palette = "Paired") +
  theme(
    legend.position = "none",
    strip.background = element_rect(fill = "#1F5736"),
    strip.text = element_text(color = "white", face = "bold", size = 8)) +
  labs(
    title = "Detect Outliers With Histogram",
    subtitle = "Plot, Histogram",
    x = NULL,
    y = NULL)

#Correlation plot
library(corrplot)
library(RColorBrewer)
corrplot(
  cor(water_clean[, -10]),
  type = "lower",
  method = "circle",
  number.cex = .9,
  order = "alphabet",
  tl.col = "#00796B",
  tl.srt = 25,
  col = brewer.pal(n = 9, name = "Purples"),
  title  = "\nCorolation Plot of Water Potability Data ")

#Correlation - numerical
library(GGally)
ggpairs(
  water_clean,
  aes(color = Potability),
  columns = 1:9,
  lower = list(continuous = wrap("smooth",alpha = 0.2,size = 0.5,color = "#DE942E")),
  diag = list(continuous = "barDiag"),
  upper = list(continuous = wrap("cor", size = 4))) +
  scale_color_manual(values = c("#1F5736", "#E94046")) +
  scale_fill_manual(values = c("#1F5736", "#E94046")) +
  theme(
    axis.text = element_text(size = 8),
    panel.background = element_rect(fill = "white"),
    strip.background = element_rect(fill = "white"),
    strip.background.x = element_rect(colour = "black"),
    strip.background.y = element_rect(colour = "black"),
    strip.text = element_text(color = "black", face = "bold", size = 8)) +
  labs(
    title = "Pair plot by Potability Var",
    subtitle = "Pair Plot, scatter plot, Histogram and Correlation coefficient",
    x = NULL,y = NULL)

```

```{r Data Split, echo=TRUE}
#Data Split
#Train and Test
set.seed(42)
water_trn_idx = sample(nrow(water_clean), size = 0.8* nrow(water_clean))
water_trn = water_clean[water_trn_idx,]
water_tst = water_clean[-water_trn_idx,]

#Estimation and Validation split
water_est_idx = sample(nrow(water_trn), size = 0.8* nrow(water_trn))
water_est = water_trn[water_est_idx,]
water_val = water_trn[-water_est_idx,]

```

```{r Normalization, echo=TRUE}
#Normalization for estimation data
water_est$ph.s = scale(water_est$ph)
ph.center = attr(water_est$ph.s,"scaled:center")
ph.scale = attr(water_est$ph.s,"scaled:scale")

water_est$Hardness.s = scale(water_est$Hardness)
Hardness.center = attr(water_est$Hardness.s,"scaled:center")
Hardness.scale = attr(water_est$Hardness.s,"scaled:scale")

water_est$Solids.s = scale(water_est$Solids)
Solids.center = attr(water_est$Solids.s,"scaled:center")
Solids.scale = attr(water_est$Solids.s,"scaled:scale")

water_est$Chloramines.s = scale(water_est$Chloramines)
Chloramines.center = attr(water_est$Chloramines.s,"scaled:center")
Chloramines.scale = attr(water_est$Chloramines.s,"scaled:scale")

water_est$Sulfate.s = scale(water_est$Sulfate)
Sulfate.center = attr(water_est$Sulfate.s,"scaled:center")
Sulfate.scale = attr(water_est$Sulfate.s,"scaled:scale")

water_est$Conductivity.s = scale(water_est$Conductivity)
Conductivity.center = attr(water_est$Conductivity.s,"scaled:center")
Conductivity.scale = attr(water_est$Conductivity.s,"scaled:scale")

water_est$Organic_carbon.s = scale(water_est$Organic_carbon)
Organic_carbon.center = attr(water_est$Organic_carbon.s,"scaled:center")
Organic_carbon.scale = attr(water_est$Organic_carbon.s,"scaled:scale")

water_est$Trihalomethanes.s = scale(water_est$Trihalomethanes)
Trihalomethanes.center = attr(water_est$Trihalomethanes.s,"scaled:center")
Trihalomethanes.scale = attr(water_est$Trihalomethanes.s,"scaled:scale")

water_est$Turbidity.s = scale(water_est$Turbidity)
Turbidity.center = attr(water_est$Turbidity.s,"scaled:center")
Turbidity.scale = attr(water_est$Turbidity.s,"scaled:scale")

water_est_norm = water_est[,10:19]
water_est_norm = water_est_norm %>% 
  select(-Potability, everything())
water_est = water_est[,1:10]


#Normalization for validation data
water_val$ph.s = scale(water_val$ph, center = ph.center, scale = ph.scale)

water_val$Hardness.s = scale(water_val$Hardness, center = Hardness.center, scale = Hardness.scale)

water_val$Solids.s = scale(water_val$Solids, center = Solids.center, scale = Solids.scale)

water_val$Chloramines.s = scale(water_val$Chloramines, center = Chloramines.center, scale = Chloramines.scale)

water_val$Sulfate.s = scale(water_val$Sulfate, center = Sulfate.center, scale = Sulfate.scale)

water_val$Conductivity.s = scale(water_val$Conductivity, center = Conductivity.center, scale = Conductivity.scale)

water_val$Organic_carbon.s = scale(water_val$Organic_carbon, center = Organic_carbon.center, scale = Organic_carbon.scale)

water_val$Trihalomethanes.s = scale(water_val$Trihalomethanes, center = Trihalomethanes.center, scale = Trihalomethanes.scale)

water_val$Turbidity.s = scale(water_val$Turbidity, center = Turbidity.center, scale = Turbidity.scale)

water_val_norm = water_val[,10:19]
water_val_norm = water_val_norm %>% 
  select(-Potability, everything())
water_val = water_val[,1:10]

calc_err = function(actual, predicted) {mean(actual != predicted)}
```

```{r Tuning, echo=TRUE}
#KNN tune
set.seed(42)
k_val = seq(1,101,by = 2)
fit_knn_to_est = function(K){
  knn3(Potability ~ ., data = water_est_norm, k = K)}
knn_mods = lapply(k_val,fit_knn_to_est)
knn_preds = lapply(knn_mods,predict,water_val_norm,type = "class")
knn_misclass = sapply(knn_preds,calc_err,actual = water_val_norm$Potability)
plot(k_val, knn_misclass,pch = 20, type = "b")
bestK = k_val[which.min(knn_misclass)]

#Decision Tree tune - cp
set.seed(42)
cp_val = seq(0,1,by = 0.001)
fit_tree_to_est = function(CP){
  rpart(Potability ~.,data = water_est, cp = CP)}

tree_mods = lapply(cp_val,fit_tree_to_est)
tree_preds = lapply(tree_mods,predict,water_val,type = "class")
tree_misclass_cp = sapply(tree_preds,calc_err,actual = water_val$Potability)
plot(cp_val, tree_misclass_cp,pch = 20, type = "b")
bestCP = cp_val[which.min(tree_misclass_cp)]

#Decision Tree tune - minsplit
set.seed(42)
ms_val = seq(10,100,by = 1)
fit_tree_to_est2 = function(MS){
  rpart(Potability ~., data = water_est,cp = 0.001, minsplit = MS)}
tree_mods2 = lapply(ms_val,fit_tree_to_est2)
tree_preds2 = lapply(tree_mods2,predict,water_val,type = "class")
tree_misclass_minsplit = sapply(tree_preds2,calc_err,actual = water_val$Potability)
plot(ms_val, tree_misclass_minsplit,pch = 20, type = "b")
bestMS = ms_val[which.min(tree_misclass_minsplit)]

table(water_est$Potability)/length(water_est$Potability)

```

```{r Fitting Models, echo=TRUE}
#classifiers to be used
water_classifiers = c("Logistic","Logistic, Poly", "LDA","LDA, Poly","LDA, Flat Prior", "QDA","QDA, Poly","QDA, Flat Prior", "Naive Bayes", "KNN", "Decision Tree")

# define flat prior
flat = c(1, 1) / 2

#fit model and calculate estimation errors
water_est_err = c(
  calc_err(water_est$Potability, predict(multinom(Potability ~ ., water_est, trace = FALSE), water_est)),
  calc_err(water_est$Potability, predict(multinom(reformulate(paste0('poly(',colnames(water_clean[-10]),',2)'),response="Potability"), water_est, trace = FALSE), water_est)),
  calc_err(water_est$Potability, predict(lda(Potability ~ ., water_est), water_est)$class),
  calc_err(water_est$Potability, predict(lda(reformulate(paste0('poly(',colnames(water_clean[-10]),',2)'),response="Potability"), water_est), water_est)$class),
  calc_err(water_est$Potability, predict(lda(Potability ~ ., water_est, prior = flat), water_est)$class),
  calc_err(water_est$Potability, predict(qda(Potability ~ ., water_est), water_est)$class),
  calc_err(water_est$Potability, predict(qda(reformulate(paste0('poly(',colnames(water_clean[-10]),',2)'),response="Potability"), water_est), water_est)$class),
  calc_err(water_est$Potability, predict(qda(Potability ~ ., water_est, prior = flat), water_est)$class),
  calc_err(water_est$Potability, predict(naiveBayes(Potability ~ ., water_est), water_est)),
  calc_err(water_est$Potability, predict(knn3(Potability ~ ., water_est_norm, k = bestK), water_est_norm, type = "class")),
  calc_err(water_est$Potability, predict(rpart(Potability ~ ., water_est, cp = bestCP, minsplit = bestMS), water_est, type = "class")))

```

```{r Validation, echo=TRUE}
# calculate validation errors
water_val_err = c(
  calc_err(water_val$Potability, predict(multinom(Potability ~ ., water_est, trace = FALSE), water_val)),
  calc_err(water_val$Potability, predict(multinom(reformulate(paste0('poly(',colnames(water_clean[-10]),',2)'),response="Potability"), water_est, trace = FALSE), water_val)),
  calc_err(water_val$Potability, predict(lda(Potability ~ ., water_est), water_val)$class),
  calc_err(water_val$Potability, predict(lda(reformulate(paste0('poly(',colnames(water_clean[-10]),',2)'),response="Potability"), water_est), water_val)$class),
  calc_err(water_val$Potability, predict(lda(Potability ~ ., water_est, prior = flat), water_val)$class),
  calc_err(water_val$Potability, predict(qda(Potability ~ ., water_est), water_val)$class),
  calc_err(water_val$Potability, predict(qda(reformulate(paste0('poly(',colnames(water_clean[-10]),',2)'),response="Potability"), water_est), water_val)$class),
  calc_err(water_val$Potability, predict(qda(Potability ~ ., water_est, prior = flat), water_val)$class),
  calc_err(water_val$Potability, predict(naiveBayes(Potability ~ ., data = water_est), water_val)),
  calc_err(water_val$Potability, predict(knn3(Potability ~ ., water_est_norm, k = bestK), water_val_norm, type = "class")),
  calc_err(water_val$Potability, predict(rpart(Potability ~ ., water_est, cp = bestCP, minsplit = bestMS), water_val, type = "class")))

# store results in data frame
water_results = data.frame(
  "No." = 1:11,
  "Method" = water_classifiers,
  "Estimation Error" = water_est_err,
  "Validation Error" = water_val_err)

water_results %>%
  kbl(caption = "Calculation of Error for each Model") %>%
  kable_classic(full_width = F, html_font = "Times New Roman")

```

```{r Final Model, echo=TRUE}

#Final Model
tree_train_error = calc_err(water_trn$Potability, predict(rpart(Potability ~ ., water_trn, cp = bestCP, minsplit = bestMS), water_trn, type = "class"))
tree_test_error = calc_err(water_tst$Potability, predict(rpart(Potability ~ ., water_trn, cp = bestCP, minsplit = bestMS), water_tst, type = "class"))
tree_model = data.frame(
  "Dataset" = "Error",
  "Train data Error" = tree_train_error,
  "Test data Error" = tree_test_error)
tree_model %>%
  kbl(caption = "Final Error For Regreesion Tree Model") %>%
  kable_classic(full_width = F, html_font = "Times New Roman")

```

